version: '3'

services:
    flask:
        container_name: car-recognizer
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - .:/app
        tty: true
        environment:
            - FLASK_ENV: 'development'
            - FLASK_APP: 'app.py'
        command: flask run --host 0.0.0.0

    